version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(submodules)"
