# Standalone home-manager on Fedora: everything the user needs comes from
# nixpkgs. Fedora itself only supplies the kernel, nix, and the login stack,
# niri included (see modules/system and install/linux/fedora.sh).
{ pkgs, ... }:

let
  # Fedora's trust store, regenerated by update-ca-trust. Preferred over
  # pkgs.cacert because CAs added on the host stay trusted. This is the
  # extracted file itself: /etc/pki/tls/certs/ca-bundle.crt is a symlink to it
  # that only exists when the openssl RPM is installed.
  caBundle = "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem";
in
{
  imports = [
    ./user.nix
    ./packages/linux.nix
  ];

  home.username = "hnbnh";
  home.homeDirectory = "/home/hnbnh";

  # Non-NixOS host: fix XDG_DATA_DIRS for nix-installed .desktop files, and
  # build /run/opengl-driver so nix-built Wayland/GL programs (wezterm, mpv,
  # ...) can use the host GPU. The driver link needs root once per mesa
  # update; install.sh runs `non-nixos-gpu-setup`, and later switches warn
  # when it must be re-run.
  targets.genericLinux.enable = true;

  # Vietnamese input: fcitx5 with the Unikey engine. The module supplies the
  # user unit and the IM variables, so only the parts specific to this host
  # are set below.
  #
  # waylandFrontend leaves GTK_IM_MODULE and QT_IM_MODULE unset so GTK and Qt
  # reach fcitx5 over niri's text-input-v3 instead of loading a toolkit
  # plugin. That is what upstream recommends, and it is also why a nix-built
  # daemon serves Fedora's own RPM applications: nothing is dlopen'd across
  # the package-manager boundary. The module still writes gtk-im-module=fcitx
  # into the GTK settings files, which XWayland applications do need.
  #
  # The group is declared here so a fresh machine needs no configtool run:
  # keyboard-us is active at login and Ctrl+Space toggles to Unikey.
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5 = {
      addons = with pkgs.qt6Packages; [
        fcitx5-unikey
        fcitx5-configtool
      ];
      waylandFrontend = true;
      settings = {
        inputMethod = {
          GroupOrder."0" = "Default";
          "Groups/0" = {
            Name = "Default";
            "Default Layout" = "us";
            DefaultIM = "keyboard-us";
          };
          "Groups/0/Items/0".Name = "keyboard-us";
          "Groups/0/Items/1".Name = "unikey";
        };
        addons.unikey.globalSection = {
          InputMethod = "Telex";
          OutputCharset = "Unicode";
        };
      };
    };
  };

  home.sessionVariables = {
    # Non-NixOS host: nix-built TLS clients have no CA bundle baked in, so
    # OpenSSL fails verification with "unable to get local issuer certificate".
    # Never hit over SSH, which does not use the X.509 trust store.
    SSL_CERT_FILE = caBundle;
    GIT_SSL_CAINFO = caBundle;
  };

  # niri has no portal of its own; its docs point at the GNOME portal for
  # screencast, with gtk for file dialogs.
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-gnome
      xdg-desktop-portal-gtk
    ];
    config.common.default = [
      "gnome"
      "gtk"
    ];
  };

  # Fedora's nix.conf is the daemon's; flakes are opted into per user.
  xdg.configFile."nix/nix.conf".text = ''
    experimental-features = nix-command flakes
  '';
}
