# Standalone home-manager on Fedora: everything the user needs comes from
# nixpkgs. Fedora itself only supplies the kernel, nix, and the login stack,
# niri included (see modules/system and install/linux/fedora.sh).
{ pkgs, ... }:

let
  ibus = pkgs.ibus-with-plugins.override { plugins = [ pkgs.ibus-engines.bamboo ]; };

  # Fedora's trust store, regenerated by update-ca-trust. Preferred over
  # pkgs.cacert because CAs added on the host stay trusted. This is the
  # extracted file itself: /etc/pki/tls/certs/ca-bundle.crt is a symlink to it
  # that only exists when the openssl RPM is installed.
  caBundle = "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem";
in
{
  imports = [
    ./user.nix
    ./packages/linux.nix
  ];

  home.username = "hnbnh";
  home.homeDirectory = "/home/hnbnh";

  # Non-NixOS host: fix XDG_DATA_DIRS for nix-installed .desktop files, and
  # build /run/opengl-driver so nix-built Wayland/GL programs (wezterm, mpv,
  # ...) can use the host GPU. The driver link needs root once per mesa
  # update; install.sh runs `non-nixos-gpu-setup`, and later switches warn
  # when it must be re-run.
  targets.genericLinux.enable = true;

  # Vietnamese input. home-manager has no ibus module, so this is what
  # NixOS's i18n.inputMethod would do: ibus with the engine baked in, plus
  # the IM variables. The daemon runs as a user unit rather than a
  # compositor autostart, so it survives a change of desktop.
  home.packages = [ ibus ];
  systemd.user.services.ibus-daemon = {
    Unit = {
      Description = "IBus input method daemon";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    # No -d: systemd wants the daemon in the foreground.
    Service = {
      ExecStart = "${ibus}/bin/ibus-daemon --replace --xim";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
  home.sessionVariables = {
    GTK_IM_MODULE = "ibus";
    QT_IM_MODULE = "ibus";
    XMODIFIERS = "@im=ibus";
    GLFW_IM_MODULE = "ibus";

    # Non-NixOS host: nix-built TLS clients have no CA bundle baked in, so
    # OpenSSL fails verification with "unable to get local issuer certificate".
    # Never hit over SSH, which does not use the X.509 trust store.
    SSL_CERT_FILE = caBundle;
    GIT_SSL_CAINFO = caBundle;
  };

  # niri has no portal of its own; its docs point at the GNOME portal for
  # screencast, with gtk for file dialogs.
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-gnome
      xdg-desktop-portal-gtk
    ];
    config.common.default = [
      "gnome"
      "gtk"
    ];
  };

  # Fedora's nix.conf is the daemon's; flakes are opted into per user.
  xdg.configFile."nix/nix.conf".text = ''
    experimental-features = nix-command flakes
  '';
}
