# HACK: Deprecated package
- name: Fix libssl.so.1.1 error
  become: true
  apt:
    deb: http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

- name: Check if rustup is installed
  shell: command -v rustup
  register: rustup_exists
  changed_when: no

- name: Install rust
  when: rustup_exists is failed
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: Update rust
  when: rustup_exists is succeeded
  shell: rustup update

- name: kitty
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

- name: mamba
  shell: curl micro.mamba.pm/install.sh | bash

#### Install packages from source ####

- name: Clone repos
  git:
    repo: "https://github.com/{{ item.user }}/{{ item.repo }}.git"
    dest: "~/.repos/{{ item.repo }}"
    single_branch: yes
    depth: 1
    version: "{{ item.branch | default('master') }}"
  loop:
    - user: junegunn
      repo: fzf
    - user: Raymo111
      repo: i3lock-color
    - user: betterlockscreen
      repo: betterlockscreen
      branch: main
    - user: vinceliuice
      repo: Orchis-theme
    - user: jarun
      repo: nnn
    - user: rvaiya
      repo: keyd

- name: Install packages from source
  shell: "{{ item.cmd }}"
  args:
    chdir: "~/.repos/{{ item.dir }}"
  loop:
    - cmd: ./install --key-bindings --completion --no-update-rc
      dir: fzf
    - cmd: ./install.sh -t green
      dir: Orchis-theme
    - cmd: ./install-i3lock-color.sh
      dir: i3lock-color

- name: Install packages from source (become)
  become: true
  shell: "{{ item.cmd }}"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.repos/{{ item.dir }}"
  loop:
    - cmd: make O_NERD=1 O_GITSTATUS=1 clean install
      dir: nnn
    - cmd: make && make install
      dir: keyd

- name: Copy binary files
  become: true
  copy:
    src: "~/.repos/{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    mode: '0755'
  loop:
    - src: betterlockscreen/betterlockscreen
      dest: betterlockscreen
    - src: nnn/nnn
      dest: nnn

- name: Install nnn plugins
  shell: curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh

#### Install packages from package manager ####

- name: Install packages with cargo
  community.general.cargo:
    name: "{{ item }}"
    state: latest
  loop:
    - hyperfine
    - fnm
    - tealdeer # tldr
    - git-delta
    - bat
    - fd-find
    - zoxide
    - starship
    - so # stackoverflow
    # Waiting for a stable release ...
    # - gobang
    - diskonaut

- name: Install packages with go
  shell: "go install {{ item }}"
  loop:
    - github.com/jesseduffield/lazygit@latest
    - github.com/jesseduffield/lazydocker@latest
    - github.com/charmbracelet/glow@latest

- name: Install packages with pip
  pip:
    name: "{{ item }}"
    extra_args: --user --upgrade
  loop:
    - ueberzug
    - yt-dlp
