- name: Check if rustup is installed
  shell: command -v rustup
  register: rustup_exists
  changed_when: no

- name: Install rust
  when: rustup_exists is failed
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: Install go
  shell: curl -LO https://get.golang.org/$(uname)/go_installer && chmod +x go_installer && ./go_installer && rm go_installer

- name: kitty
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

- name: mamba
  shell: curl micro.mamba.pm/install.sh | bash
