- include_tasks: repos.yml

- name: Install the 'Development tools' package group
  become: true
  dnf:
    name: '@Development tools'
    state: present

- name: Install packages from repository
  become: true
  dnf:
    name:
      - python3-pip
      - ufw
      - util-linux-user
      - zsh

      # Dev tools
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
      - libtool
      - libyaml
      - perl

      # cli
      - ImageMagick
      - aria2
      - asciinema
      - bat
      - brightnessctl
      - diskonaut
      - djvulibre # DjVu utilities
      - fd-find
      - ffmpeg-free
      - ffmpegthumbs
      - fzf
      - gammastep
      - git-delta
      - gnome-epub-thumbnailer
      - hyperfine
      - navi
      - poppler-utils # pdf to image
      - ripgrep
      - swaybg
      - tealdeer # tldr
      - torbrowser-launcher
      - yt-dlp
      - zoxide

      # gui
      - calibre
      - chromium
      - flameshot
      - ibus
      - kitty
      - lxappearance
      - mpv
      - network-manager-applet
      - obs-studio
      - papirus-icon-theme
      - rofi
      - rofimoji
      - waybar
      - wine
      - xournalpp
      - zathura

      # tui
      - neovim

      # languages
      - cargo
      - golang
      - rust

      # ========== THIRD-PARTY REPOS ========= #

      # cli
      - gh # github

      # docker
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

      # Input method
      - ibus-bamboo # Vietnamese

    state: latest

- name: Remove packages
  become: true
  dnf:
    name:
      - dnf-automatic
    state: absent


- include_tasks: nix.yml
- include_tasks: releases.yml
- include_tasks: post-install.yml
