- include_tasks: repos.yml
- include_tasks: corp.yml

- name: Install the 'Development tools' package group
  become: true
  dnf:
    name: "@Development tools"
    state: present

- name: Install packages from repository
  become: true
  dnf:
    name:
      - blueman
      - ibus
      - ibus-bamboo # Vietnamese input method
      - network-manager-applet
      - obs-studio
      - papirus-icon-theme
      - swappy
      - xournalpp
      - zathura
      - zsh

    state: latest

- name: Remove packages
  become: true
  dnf:
    name:
      - dnf-automatic
    state: absent

- include_tasks: post-install.yml
