- include_tasks: repos.yml

- name: Install the 'Development tools' package group
  become: true
  dnf:
    name: '@Development tools'
    state: present

- name: Install packages from repository
  become: true
  dnf:
    name:
      - zsh

      # cli
      - ImageMagick
      - aria2
      - asciinema
      - bat
      - brightnessctl
      - diskonaut
      - djvulibre # DjVu utilities
      - fd-find
      - ffmpeg-free
      - ffmpegthumbs
      - fzf
      - gammastep
      - git-delta
      - gnome-epub-thumbnailer
      - hyperfine
      - navi
      - poppler-utils # pdf to image
      - ripgrep
      - tealdeer # tldr
      - torbrowser-launcher
      - yt-dlp
      - zoxide

      # gui
      - chromium
      - flameshot
      - ibus
      - lxappearance
      - mpv
      - obs-studio
      - papirus-icon-theme
      - rofi
      - wine
      - xournalpp
      - zathura
      - kitty

      # tui
      - neovim

      # languages
      - cargo
      - rust
      - golang

      # ========== THIRD-PARTY REPOS ========= #

      # cli
      - gh # github

      # docker
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

      # Input method
      - ibus-bamboo # Vietnamese

    state: latest

- include_tasks: nix.yml
- include_tasks: releases.yml
- include_tasks: post-install.yml
