- name: Install packages with cargo
  community.general.cargo:
    name: "{{ item | split('@') | first }}"
    version: "{{ item | split('@') | last }}"
  loop:
    - hyperfine@1.15.0
    - fnm@1.32.0
    - tealdeer@1.6.1 # tldr
    - git-delta@0.15.1
    - bat@0.22.1
    - fd-find@8.6.0
    - zoxide@0.9.0
    - starship@1.12.0
    - so@0.4.9 # stackoverflow
    # Waiting for a stable release ...
    # - gobang
    - diskonaut@0.11.0
    - kdash@0.3.6
    - rtx-cli@1.30.1

- name: Install packages with go
  shell: "go install {{ item }}"
  loop:
    - github.com/jesseduffield/lazygit@v0.36.0
    - github.com/jesseduffield/lazydocker@v0.20.0
    - github.com/charmbracelet/glow@v1.4.1

- name: Install packages with pip
  pip:
    name: "{{ item }}"
    extra_args: --user --upgrade
  loop:
    - yt-dlp==2023.01.06
