- name: Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to some groups
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: "{{ item.groups }}"
    append: yes
  loop:
    - groups: docker
    - groups: libvirt
    - groups: kvm

- name: Post install (become)
  become: true
  shell: |
    chsh -s $(which zsh)
    cp $(which keyd) /usr/bin/keyd
  changed_when: no

# TODO: Commit plugins directory
- name: Install nnn plugins
  shell: curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh
