#!/bin/bash

function have {
  command -v "$1" &>/dev/null
}

function install_dots {
  CFG_DIR="$HOME/dotfiles/config"
  DEST_DIR="$HOME/.config"

  mkdir -p $DEST_DIR

  for dir in "$CFG_DIR"/*/; do
    ln -sfnv $dir $DEST_DIR
  done

  ln -sfnv "$CFG_DIR/zsh/.zshrc" "$HOME/.zshrc"
  ln -sfnv "$CFG_DIR/zsh/.zshenv" "$HOME/.zshenv"
  ln -sfnv "$CFG_DIR/zsh/.zimrc" "$HOME/.zimrc"
  ln -sfnv "$CFG_DIR/git/.gitconfig" "$HOME/.gitconfig"

  ln -sfnv "$CFG_DIR/agent-os" "$HOME/agent-os"
  ln -sfnv "$CFG_DIR/.claude" "$HOME/.claude"
  ln -sfnv "$CFG_DIR/.cursor" "$HOME/.cursor"
  ln -sfnv "$CFG_DIR/.codex" "$HOME/.codex"
  ln -sfnv "$CFG_DIR/.gemini" "$HOME/.gemini"
}
