- name: Link dotfiles
  command: "{{ ansible_env.HOME }}/dotfiles/bin/relink --apply"
  register: relink
  changed_when: relink.stdout is regex('[1-9][0-9]* applied')
  failed_when: relink.rc > 1

- name: Install required packages
  pip:
    name: "{{ item }}"
  loop:
    - psutil

- name: ibus config
  dconf:
    key: "/desktop/ibus/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ IBUS_CONFIG | dict2items }}"
