- name: Create ~/.config
  file:
    path: ~/.config
    state: directory

- name: Find .config files
  find:
    paths: ~/dotfiles/config/
    recurse: no
    file_type: any
    hidden: yes
  register: dot_config

- name: ~/.config/
  file:
    src: "{{item.path}}"
    dest: "~/.config/{{item.path | basename}}"
    state: link
  loop: "{{ dot_config.files }}"
  loop_control:
    label: "~/.config/{{item.path | basename}}"

- name: Link files
  file:
    src: "~/.config/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    state: link
  loop:
    - src: zsh/.zshrc
      dest: .zshrc
    - src: zsh/.zimrc
      dest: .zimrc
    - src: git/.gitconfig
      dest: .gitconfig
    - src: tmux/.tmux.conf
      dest: .tmux.conf
    - src: betterlockscreen/betterlockscreenrc
      dest: .config/betterlockscreenrc
    - src: ripgrep/.ripgreprc
      dest: .ripgreprc
    - src: yt-dlp/yt-dlp.conf
      dest: yt-dlp.conf

- name: ibus config
  dconf:
    key: "/desktop/ibus/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ IBUS_CONFIG | dict2items }}"
