- name: Customize /etc/environment
  become: true
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - key: EDITOR
      value: nvim
    - key: GTK_IM_MODULE
      value: ibus
    - key: QT_IM_MODULE
      value: ibus
    - key: XMODIFIERS
      value: "@im=ibus"
    - key: QT4_IM_MODULE
      value: ibus
    - key: CLUTTER_IM_MODULE
      value: ibus
    - key: GLFW_IM_MODULE
      value: ibus

- name: systemd
  become: true
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  loop:
    - name: NetworkManager-wait-online.service
      enabled: no
      state: stopped

- name: Enable firewall
  become: true
  community.general.ufw:
    state: enabled
    policy: allow
