# vim: ft=tmux

set -g @yank_action 'copy-pipe'
# nixpkgs' resurrect predates the XDG default
set -g @resurrect-dir '~/.local/share/tmux/resurrect'

run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.config/tmux/plugins/tmux-yank/yank.tmux
