- name: Chmod bin
  file:
    path: ~/dotfiles/bin/
    recurse: yes
    mode: 0755

- name: Create ~/.local/bin
  file:
    path: ~/.local/bin
    state: directory

- name: Find bin files
  find:
    paths: ~/dotfiles/bin/
    recurse: no
    file_type: any
  register: bin

- name: ~/.local/bin
  file:
    src: "{{item.path}}"
    dest: "~/.local/bin/{{item.path | basename}}"
    state: link
  loop: "{{ bin.files }}"
  loop_control:
    label: "~/.local/bin/{{item.path | basename}}"
