- name: Create {{item}} directory
  file:
    path: ~/.local/share/fonts/{{item}}
    state: directory

- name: Installing {{item}}
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{item}}.zip
    dest: ~/.local/share/fonts/{{item}}
    creates: ~/.local/share/fonts/{{item}}/done
    remote_src: true
  notify: update font cache

- name: Installed {{item}}
  copy:
    dest: ~/.local/share/fonts/{{item}}/done
    content: ""
